apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 3
  selector:
    app: get-started
  template:
    metadata:
      labels:
        app: get-started
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: get-started
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: http-port
          containerPort: 80
