---
apiVersion: v1
kind: Service
metadata:
  name: python-webapp-svc
spec:
  ports:
  - port: 31007
    nodePort: 31007
    targetPort: 8081
    protocol: TCP
  selector:
    app: python-webapp
  type: NodePort
